### 1) Register a new user
POST http://127.0.0.1:8000/api/users/register/
Content-Type: application/json

{
  "email": "amir@example.com",
  "password": "12345678"
}

### 2) Login (get your token)
POST http://127.0.0.1:8000/api/users/login/
Content-Type: application/json

{
  "email": "amir@example.com",
  "password": "12345678"
}

### 3) Get authenticated user info
GET http://127.0.0.1:8000/api/users/user/
Authorization: Token 9806619190dc912ca96f25c560d95516277cd7a5

### 4) Create a deposit request
POST http://127.0.0.1:8000/api/deposits/
Content-Type: application/json
Authorization: Token 9806619190dc912ca96f25c560d95516277cd7a5

{
  "amount": 1000.00,
  "currency": "USDT",
  "trx_id":   "trx12345678"
}

### 5) List your deposit requests
GET http://127.0.0.1:8000/api/deposits/
Authorization: Token 9806619190dc912ca96f25c560d95516277cd7a5
