# Generated by Django 5.2 on 2025-04-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0002_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='user',
        ),
        migrations.AddField(
            model_name='deposit',
            name='currency',
            field=models.CharField(default='USDT', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposit',
            name='trx_id',
            field=models.CharField(default='USDT', max_length=50),
            preserve_default=False,
        ),
    ]
