# Generated by Django 5.2 on 2025-05-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0005_alter_deposit_amount_alter_deposit_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='trx_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
